# Generated by Django 3.1.5 on 2021-01-26 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitt', '0006_auto_20210126_1849'),
        ('prof', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.follow')),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitt.like')),
                ('retwitt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitt.retwitt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
