# Generated by Django 3.1.5 on 2021-01-26 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0002_auto_20210126_2123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
