# Generated by Django 3.1.5 on 2021-01-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0002_userprofile_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_modif',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
