# Generated by Django 3.1.5 on 2021-01-25 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0003_auto_20210125_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_modif',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
