# Generated by Django 3.1.5 on 2021-01-27 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0004_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='update_follow',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='update_like',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='update_retwitt',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
