# Generated by Django 3.1.5 on 2021-01-25 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0004_auto_20210125_1851'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('user', 'target')},
        ),
    ]
