# Generated by Django 3.1.5 on 2021-01-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0005_auto_20210127_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='update_follow',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='update_like',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='update_retwitt',
            field=models.BooleanField(default=False),
        ),
    ]
