# Generated by Django 3.1.5 on 2021-01-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0006_auto_20210127_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
