# Generated by Django 3.1.5 on 2021-01-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitt', '0004_auto_20210126_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='lastupdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
