# Generated by Django 3.1.5 on 2021-01-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitt', '0006_auto_20210126_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='occurrences',
            field=models.PositiveIntegerField(auto_created=True, default=0),
        ),
    ]
